language: node_js
node_js:
  - "10.13.0"
services:
  - mongodb
script:
  - yarn build
cache:
  directories: -node_modules

# deploy:
#   provider: heroku
#   api_key: ...
#   app:
#     master: teamcomm2
