export const REG_CALLED = "REG_CALLED";
export const REG_RETURNED = "REG_RETURNED";
export const REG_ERROR = "REG_ERROR";

export const LOGIN_CALLED = "LOGIN_CALLED";
export const LOGIN_RETURNED = "LOGIN_RETURNED";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGOUT_CALLED = "LOGOUT_CALLED";

export const UPDATE_CALLED = "UPDATE_CALLED";
export const UPDATE_RETURNED = "UPDATE_RETURNED";

export const GOOGLE_LOGIN_CALLED = "GOOGLE_LOGIN_CALLED";
export const GOOGLE_LOGIN_RETURNED = "GOOGLE_LOGIN_RETURNED";

export const TOGGLE_OVERPANE = "TOGGLE_OVERPANE";
export const TOGGLE_MOBILE_MENU = "TOGGLE_MENU";

export const CREATE_MEETING_CALLED = "CREATE_MEETING_CALLED";
export const CREATE_MEETING_RETURNED = "CREATE_MEETING_RETURNED";

export const GET_MEETING_CALLED = "GET_MEETING_CALLED";
export const GET_MEETING_RETURNED = "GET_MEETING_RETURNED";

export const MEETING_UPDATE_CALLED = "MEETING_UPDATE_CALLED";
export const MEETING_UPDATE_RETURNED = "MEETING_UPDATE_RETURNED";

export const DELETE_MEETING_CALLED = "DELETE_MEETING_CALLED";
export const DELETE_MEETING_RETURNED = "DELETE_MEETING_RETURNED";

export const PREMIUM_CHANGE = "PREMIUM_CHANGE";
