export const REG_CALLED = "REG_CALLED";
export const REG_RETURNED = "REG_RETURNED";

export const LOGIN_CALLED = "LOGIN_CALLED";
export const LOGIN_RETURNED = "LOGIN_RETURNED";

export const LOGOUT_CALLED = "LOGOUT_CALLED";

export const GOOGLE_LOGIN_CALLED = "GOOGLE_LOGIN_CALLED";
export const GOOGLE_LOGIN_RETURNED = "GOOGLE_LOGIN_RETURNED";

export const TOGGLE_OVERPANE = "TOGGLE_OVERPANE";
